# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141619)
$foreground = rgb(F9D9B8)
$color0 = rgb(3B3D41)
$color1 = rgb(1E131C)
$color2 = rgb(320B1D)
$color3 = rgb(4C181A)
$color4 = rgb(50191A)
$color5 = rgb(9C4320)
$color6 = rgb(B26D26)
$color7 = rgb(EEC090)
$color8 = rgb(A68665)
$color9 = rgb(281926)
$color10 = rgb(430F27)
$color11 = rgb(652023)
$color12 = rgb(6B2123)
$color13 = rgb(D0592B)
$color14 = rgb(ED9133)
$color15 = rgb(EEC090)
