# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(0E0B04)
$foreground = rgb(FAF9F8)
$color0 = rgb(0E0B04)
$color1 = rgb(262421)
$color2 = rgb(38362A)
$color3 = rgb(4E4E37)
$color4 = rgb(6A6B62)
$color5 = rgb(89882B)
$color6 = rgb(B6B374)
$color7 = rgb(FAF9F8)
$color8 = rgb(23221E)
$color9 = rgb(262421)
$color10 = rgb(38362A)
$color11 = rgb(4E4E37)
$color12 = rgb(6A6B62)
$color13 = rgb(89882B)
$color14 = rgb(B6B374)
$color15 = rgb(FAF9F8)
