# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141A23)
$foreground = rgb(D3E9F6)
$color0 = rgb(292F39)
$color1 = rgb(A85929)
$color2 = rgb(A45C31)
$color3 = rgb(84746B)
$color4 = rgb(73828C)
$color5 = rgb(96806D)
$color6 = rgb(6190AC)
$color7 = rgb(B8D7EA)
$color8 = rgb(8096A4)
$color9 = rgb(E07637)
$color10 = rgb(DA7B42)
$color11 = rgb(B19B8E)
$color12 = rgb(99ADBA)
$color13 = rgb(C8AA91)
$color14 = rgb(81C0E6)
$color15 = rgb(B8D7EA)
