-- Desktop capability keybinds.

local mod = USER.mainMod
local function keys(...)
  return table.concat({...}, " + ")
end

hl.bind(keys(mod, "Return"), hl.dsp.exec_cmd(USER.terminal))
hl.bind(keys(mod, "E"), hl.dsp.exec_cmd(USER.files))
hl.bind(keys(mod, "B"), hl.dsp.exec_cmd(USER.browser))
hl.bind(keys(mod, "A"), hl.dsp.exec_cmd("pkill rofi || true; rofi -show drun -modi drun,filebrowser,run,window"))
hl.bind(keys(mod, "D"), hl.dsp.exec_cmd("anyrun"))
hl.bind(keys(mod, "L"), hl.dsp.exec_cmd("hyprlock"))
hl.bind(keys(mod, "H"), hl.dsp.exec_cmd(ATLAS.automation .. "/info/keyhints.sh"))
hl.bind(keys(mod, "ALT", "R"), hl.dsp.exec_cmd(ATLAS.automation .. "/desktop/refresh.sh"))
hl.bind(keys(mod, "ALT", "E"), hl.dsp.exec_cmd(ATLAS.automation .. "/launchers/rofi-emoji.sh"))
hl.bind(keys(mod, "S"), hl.dsp.exec_cmd(ATLAS.automation .. "/launchers/rofi-search.sh"))
hl.bind(keys(mod, "CTRL", "S"), hl.dsp.exec_cmd("rofi -show window"))
hl.bind(keys(mod, "ALT", "O"), hl.dsp.exec_cmd(ATLAS.automation .. "/compositor/blur.sh"))
hl.bind(keys(mod, "ALT", "L"), hl.dsp.exec_cmd(ATLAS.automation .. "/compositor/layout.sh"))
hl.bind(keys(mod, "ALT", "V"), hl.dsp.exec_cmd(ATLAS.automation .. "/launchers/clip-manager.sh"))
hl.bind(keys(mod, "CTRL", "R"), hl.dsp.exec_cmd(ATLAS.automation .. "/launchers/rofi-themes.sh"))
hl.bind(keys(mod, "W"), hl.dsp.exec_cmd(ATLAS.automation .. "/theming/wallpaper-select.sh"))
hl.bind(keys(mod, "SHIFT", "W"), hl.dsp.exec_cmd(ATLAS.automation .. "/theming/wallpaper-effects.sh"))
hl.bind(keys("CTRL", "ALT", "W"), hl.dsp.exec_cmd(ATLAS.automation .. "/theming/wallpaper-random.sh"))
hl.bind(keys(mod, "SHIFT", "E"), hl.dsp.exec_cmd(ATLAS.automation .. "/desktop/quick-settings.sh"))
hl.bind(keys(mod, "SHIFT", "G"), hl.dsp.exec_cmd(ATLAS.automation .. "/compositor/game-mode.sh"))
hl.bind(keys(mod, "N"), hl.dsp.exec_cmd(ATLAS.automation .. "/display/hyprsunset.sh toggle"))
hl.bind(keys(mod, "CTRL", "ALT", "B"), hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"))
hl.bind(keys(mod, "CTRL", "B"), hl.dsp.exec_cmd(ATLAS.automation .. "/desktop/waybar-styles.sh"))
hl.bind(keys(mod, "ALT", "B"), hl.dsp.exec_cmd(ATLAS.automation .. "/desktop/waybar-layout.sh"))
hl.bind(keys(mod, "SHIFT", "M"), hl.dsp.exec_cmd(ATLAS.automation .. "/launchers/rofi-beats.sh"))
hl.bind(keys(mod, "SHIFT", "K"), hl.dsp.exec_cmd(ATLAS.automation .. "/info/keybinds.sh"))
hl.bind(keys(mod, "SHIFT", "A"), hl.dsp.exec_cmd(ATLAS.automation .. "/compositor/animations.sh"))
hl.bind(keys(mod, "SHIFT", "O"), hl.dsp.exec_cmd(ATLAS.automation .. "/theming/zsh-theme.sh"))
hl.bind(keys(mod, "ALT", "C"), hl.dsp.exec_cmd(ATLAS.automation .. "/launchers/rofi-calc.sh"))
hl.bind(keys(mod, "SHIFT", "Return"), hl.dsp.exec_cmd(ATLAS.automation .. "/session/drop-terminal.sh " .. USER.terminal))
hl.bind(keys("CTRL", "ALT", "L"), hl.dsp.exec_cmd(ATLAS.automation .. "/session/lock.sh"))
hl.bind(keys("CTRL", "ALT", "P"), hl.dsp.exec_cmd(ATLAS.automation .. "/session/logout.sh"))
hl.bind(keys(mod, "SHIFT", "N"), hl.dsp.exec_cmd("swaync-client -t -sw"))
